import pandas as pd


class DbtModelGenerator:
    """Generate dbt model SQL and YAML from table metadata.

    This shows clients you understand modern data stack (dbt, Snowflake, etc.)
    """

    @staticmethod
    def generate_staging_model(table_name: str, schema: pd.DataFrame) -> str:
        columns = schema["column_name"].tolist()
        col_list = ",\n        ".join(columns)

        return f"""-- generated by AI Data Analyst Agent
-- staging model for {table_name}

WITH source AS (
    SELECT * FROM {{{{ source('raw', '{table_name}') }}}}
),

staged AS (
    SELECT
        {col_list}
    FROM source
)

SELECT * FROM staged
"""

    @staticmethod
    def generate_schema_yaml(table_name: str, schema: pd.DataFrame, stats: dict | None = None) -> str:
        yaml_lines = [
            "version: 2",
            "",
            "models:",
            f"  - name: stg_{table_name}",
            f'    description: "Staging model for {table_name}"',
            "    columns:",
        ]

        for _, row in schema.iterrows():
            col_name = row["column_name"]
            col_type = row["column_type"]
            yaml_lines.append(f"      - name: {col_name}")
            yaml_lines.append(f'        description: "{col_type} column"')

            if stats and col_name in stats.get("columns", {}):
                col_stats = stats["columns"][col_name]
                if col_stats.get("nulls", 0) == 0:
                    yaml_lines.append("        tests:")
                    yaml_lines.append("          - not_null")
                if col_stats.get("distinct", 0) == stats.get("row_count", 0) and stats.get("row_count", 0) > 0:
                    yaml_lines.append("        tests:")
                    yaml_lines.append("          - unique")

        return "\n".join(yaml_lines)

    @staticmethod
    def generate_source_yaml(table_name: str, database: str = "raw_db", schema_name: str = "raw") -> str:
        return f"""version: 2

sources:
  - name: {schema_name}
    database: {database}
    schema: {schema_name}
    tables:
      - name: {table_name}
        description: "Raw {table_name} data"
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {{count: 12, period: hour}}
          error_after: {{count: 24, period: hour}}
"""
